


ALPACA_API_KEY = "PKERRV3YTCV45EKWH4OA773Z37" 
ALPACA_SECRET_KEY = "F4g6QV6ciEKk5Jydpnt8tEQCHxZfW9A4tt1YTA2AsLm7"  
USE_PAPER_TRADING = True  

WATCHLIST = [
    "TQQQ",    
    "SOXL",    
    "UPRO",    
    "BTCUSD"  
]

SMA_FAST = 20        
SMA_SLOW = 50         
ROC_PERIOD = 10       


TOP_LONGS = 2
BOTTOM_SHORTS = 1    

TAKE_PROFIT_PCT = 0.10  

MAX_TRADES_PER_DAY = 10    
COOLDOWN_DAYS = 2           
MAX_POSITION_PCT = 0.30     
MAX_GROSS_EXPOSURE = 1.5   

STORE_FILE = "bot_store.json"  